apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: test-ci-cd-sigemad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: image-registry.openshift-image-registry.svc:5000/test-ci-cd-sigemad/frontend:latest  # Cambia al tag correcto
        ports:
        - containerPort: 80

