apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: test-ci-cd-sigemad
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP  # Cambia a LoadBalancer si necesitas acceso externo

