apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: test-ci-cd-sigemad
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP  # Cambia a LoadBalancer si necesitas acceso externo

